### ISSUE TITLE
\Chip\Model\Billing\Purchase does not exist

### ISSUE THREAD

**Issue by MSufianS** [CHIPAsia/chip-php-sdk#11]
Hi,

I encountered the following error while attempting to execute the addBillingTemplateSubscriber function

`"Class "\Chip\Model\Billing\Purchase" does not exist"`

**Comment by wzul** [comment]
I'm able to replicate this error too with this code:

```php
<?php

require 'vendor/autoload.php';

$brand_id = '';
$secret_key = '';

$billing_template_id = '5cbc2f7a-2fe7-4e4b-8a42-bb6ab1a4b266';
$client_id = '7e90da80-d749-4595-9a98-4dfdd7e2d536';

$btc = new \Chip\Model\Billing\BillingTemplateClient;
$btc->client_id = $client_id;

$chip = new \Chip\ChipApi($brand_id, $secret_key);
$result = $chip->addBillingTemplateSubscriber($billing_template_id, $btc); // error thrown here

echo print_r($result, true);
```

That's because PHP is using `@var` Purchase type hinting declared in the comment where Purchase class is not relative to that namespace. 

I have reviewed your PR and suggested for change. 

Thanks!
